export const getPanelTabScreenOptions = (palette) => ({
  tabBarActiveTintColor: palette.activeTint,
  tabBarInactiveTintColor: palette.softText,
  tabBarActiveBackgroundColor: 'transparent',
  tabBarBadgeStyle: { backgroundColor: palette.red, color: palette.onBrand, fontWeight: '900' },
  tabBarLabelStyle: { fontSize: 11, fontWeight: '900' },
  tabBarItemStyle: {
    borderRadius: 14,
    marginHorizontal: 3,
    marginVertical: 7,
    paddingVertical: 2,
  },
  tabBarStyle: {
    backgroundColor: palette.white,
    borderColor: palette.border,
    borderRadius: 18,
    borderTopWidth: 1,
    borderWidth: 1,
    bottom: 10,
    boxShadow: `0 10px 28px ${palette.shadow}`,
    elevation: 10,
    height: 72,
    left: 8,
    paddingBottom: 8,
    paddingHorizontal: 6,
    paddingTop: 8,
    position: 'absolute',
    right: 8,
  },
  animation: 'shift',
  sceneStyle: { backgroundColor: palette.appBg },
  transitionSpec: {
    animation: 'timing',
    config: { duration: 180 },
  },
  headerShown: false,
});
